# =============================================================================
# IMAGEN PLATFORM - CLOUD BUILD CI/CD (TRITON ARCHITECTURE)
# =============================================================================
#
# Builds and deploys:
# - API image → Cloud Run
# - Worker image → For thin workers (CPU-only)
# - Triton image → Centralized GPU inference
#
# Triggers:
#   - Push to main branch → Deploy to production
#   - Push to develop branch → Deploy to dev
#   - Pull request → Build only (no deploy)
#
# =============================================================================

timeout: 2400s  # 40 minutes (Triton image is large)

substitutions:
  _REGION: us-central1
  _GKE_CLUSTER: imagen-cluster
  _NAMESPACE: imagen

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # ===========================================================================
  # STEP 1: Build API Docker Image
  # ===========================================================================
  - id: 'build-api'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/api:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/api:latest'
      - '-f'
      - 'docker/Dockerfile.api'
      - '.'

  # ===========================================================================
  # STEP 2: Build Worker Docker Image (for thin workers)
  # ===========================================================================
  - id: 'build-worker'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/worker:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/worker:latest'
      - '-f'
      - 'docker/Dockerfile.worker'
      - '.'

  # ===========================================================================
  # STEP 3: Build Triton Docker Image
  # ===========================================================================
  - id: 'build-triton'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/triton:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/triton:latest'
      - '-f'
      - 'triton/Dockerfile'
      - '.'

  # ===========================================================================
  # STEP 4: Push API Image
  # ===========================================================================
  - id: 'push-api'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/api'
    waitFor:
      - 'build-api'

  # ===========================================================================
  # STEP 5: Push Worker Image
  # ===========================================================================
  - id: 'push-worker'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/worker'
    waitFor:
      - 'build-worker'

  # ===========================================================================
  # STEP 6: Push Triton Image
  # ===========================================================================
  - id: 'push-triton'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/triton'
    waitFor:
      - 'build-triton'

  # ===========================================================================
  # STEP 7: Deploy API to Cloud Run
  # ===========================================================================
  - id: 'deploy-api'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'imagen-api'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/api:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID},GCS_BUCKET=${PROJECT_ID}-imagen-images'
    waitFor:
      - 'push-api'

  # ===========================================================================
  # STEP 8: Get GKE Credentials
  # ===========================================================================
  - id: 'gke-credentials'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '${_GKE_CLUSTER}'
      - '--region'
      - '${_REGION}'
      - '--project'
      - '${PROJECT_ID}'
    waitFor:
      - 'push-worker'
      - 'push-triton'

  # ===========================================================================
  # STEP 9: Update Image Tags in K8s Manifests
  # ===========================================================================
  - id: 'update-k8s-manifests'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Update worker image in workers manifests
        for file in k8s/workers/*.yaml; do
          sed -i "s|image:.*worker.*|image: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/worker:${SHORT_SHA}|g" "$file"
        done
        
        # Update Triton image
        sed -i "s|image:.*triton.*|image: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/triton:${SHORT_SHA}|g" k8s/triton/deployment.yaml
    waitFor:
      - 'gke-credentials'

  # ===========================================================================
  # STEP 10: Deploy K8s Base Resources
  # ===========================================================================
  - id: 'deploy-k8s-base'
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/base/'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
    waitFor:
      - 'update-k8s-manifests'

  # ===========================================================================
  # STEP 11: Deploy Triton Inference Server
  # ===========================================================================
  - id: 'deploy-triton'
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/triton/'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
    waitFor:
      - 'deploy-k8s-base'

  # ===========================================================================
  # STEP 12: Wait for Triton to be Ready
  # ===========================================================================
  - id: 'wait-for-triton'
    name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting for Triton to be ready..."
        kubectl rollout status deployment/triton-inference-server -n ${_NAMESPACE} --timeout=600s
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
    waitFor:
      - 'deploy-triton'

  # ===========================================================================
  # STEP 13: Deploy Workers (CPU-only)
  # ===========================================================================
  - id: 'deploy-workers'
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/workers/'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
    waitFor:
      - 'wait-for-triton'

  # ===========================================================================
  # STEP 14: Deploy Auto-scaling (HPA)
  # ===========================================================================
  - id: 'deploy-autoscaling'
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/autoscaling/'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
    waitFor:
      - 'deploy-workers'

  # ===========================================================================
  # STEP 15: Deploy Monitoring
  # ===========================================================================
  - id: 'deploy-monitoring'
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/monitoring/'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
    waitFor:
      - 'deploy-autoscaling'

  # ===========================================================================
  # STEP 16: Verify Deployment
  # ===========================================================================
  - id: 'verify-deployment'
    name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=============================================="
        echo "         DEPLOYMENT STATUS                    "
        echo "=============================================="
        echo ""
        echo "=== Triton Inference Server ==="
        kubectl get pods -n ${_NAMESPACE} -l app=triton
        echo ""
        echo "=== Workers (CPU-only) ==="
        kubectl get pods -n ${_NAMESPACE} -l app.kubernetes.io/component=worker
        echo ""
        echo "=== HPAs ==="
        kubectl get hpa -n ${_NAMESPACE}
        echo ""
        echo "=== Services ==="
        kubectl get svc -n ${_NAMESPACE}
        echo ""
        echo "=============================================="
        echo "         DEPLOYMENT COMPLETE                  "
        echo "=============================================="
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
    waitFor:
      - 'deploy-monitoring'

# ===========================================================================
# ARTIFACTS
# ===========================================================================
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/api:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/api:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/worker:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/worker:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/triton:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/imagen/triton:latest'
