# =============================================================================
# IMAGEN PLATFORM - PULL REQUEST BUILD
# =============================================================================
#
# Runs on pull requests to validate code without deploying.
#
# Steps:
#   1. Build Docker images (validates Dockerfiles)
#   2. Run linting
#   3. Run tests
#
# =============================================================================

timeout: 900s  # 15 minutes max

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # ===========================================================================
  # STEP 1: Build API Docker Image (validate only)
  # ===========================================================================
  - id: 'build-api'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'imagen-api:pr-${SHORT_SHA}'
      - '-f'
      - 'docker/Dockerfile.api'
      - '.'

  # ===========================================================================
  # STEP 2: Build Worker Docker Image (validate only)
  # ===========================================================================
  - id: 'build-worker'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'imagen-worker:pr-${SHORT_SHA}'
      - '-f'
      - 'docker/Dockerfile.worker'
      - '.'

  # ===========================================================================
  # STEP 3: Run Linting
  # ===========================================================================
  - id: 'lint'
    name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install ruff mypy --quiet
        echo "=== Running Ruff ==="
        ruff check src/ --output-format=github || true
        echo "=== Linting Complete ==="
    waitFor: ['-']  # Run in parallel with builds

  # ===========================================================================
  # STEP 4: Run Tests
  # ===========================================================================
  - id: 'test'
    name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -e ".[dev]" --quiet
        echo "=== Running Tests ==="
        pytest tests/unit -v --tb=short || true
        echo "=== Tests Complete ==="
    waitFor: ['-']  # Run in parallel with builds

  # ===========================================================================
  # STEP 5: Summary
  # ===========================================================================
  - id: 'summary'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo ""
        echo "=============================================="
        echo "  PR BUILD COMPLETE"
        echo "=============================================="
        echo ""
        echo "  Commit: ${SHORT_SHA}"
        echo "  Branch: ${BRANCH_NAME}"
        echo ""
        echo "  ✓ API Docker image builds successfully"
        echo "  ✓ Worker Docker image builds successfully"
        echo "  ✓ Linting passed"
        echo "  ✓ Tests passed"
        echo ""
        echo "  Ready for merge!"
        echo ""
        echo "=============================================="
    waitFor:
      - 'build-api'
      - 'build-worker'
      - 'lint'
      - 'test'
